### ISSUE TITLE
Is the brightness slider, sd card reader, fingerprint sensor working?

### ISSUE THREAD

**Issue by gnpaone** [qkdxorjs1002/Config-Hackintosh-X403FA#1]

**Comment by qkdxorjs1002** [comment]
@gnpaone 
Hi, Both of brightness and SD reader is working. 
But, fingerprint sensor(including Touch ID feature) is not work because there's no working fingerprint driver with macOs.
If you want to know more details, check out these 'Connectivity' and 'Human Interface Devices' of [Link](https://github.com/qkdxorjs1002/Config-Hackintosh-X403FA#connectivity).

**Comment by gnpaone** [comment]
Thanks for the reply. For me sd card reader and brightness both are not working. Can you please tell how you get it to work?

**Comment by qkdxorjs1002** [comment]
@gnpaone Sorry for the late reply.
Actually I don't have remember that I confirmed the working of  SDCard Reader and Brightness with 15.6.
I suggest trying test with latest commit on ~15.5.
